name = "SequenceComparator"
uuid = "a5622758-c379-4ffb-953e-c2340219cda7"
authors = ["Nick Bui <nicholasbui14@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FastLevenshtein = "f79185a3-a88d-4013-8848-f9f041a6cb9a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
